name: API Server - CI

on:
  push:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          token: ${{secrets.ACTION_TOKEN}}
          submodules: true

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: init with Gradle
        uses: gradle/gradle-build-action@v2

      - run: gradle init

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.6.1
          arguments: build
          
